# Generated by Django 5.0.14 on 2025-05-14 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "victima_app",
            "0002_remove_productos_descripcion_beneficiarios_apellido_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="beneficiarios",
            options={"ordering": ["fecha_registro"]},
        ),
        migrations.AlterModelOptions(
            name="contratos",
            options={"ordering": ["-fecha_registro"]},
        ),
        migrations.AddField(
            model_name="beneficiarios",
            name="estado",
            field=models.CharField(
                choices=[("pendiente", "Pendiente"), ("procesado", "Procesado")],
                default="pendiente",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="beneficiarios",
            name="fecha_registro",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="contratos",
            name="fecha_registro",
            field=models.DateField(auto_now_add=True),
        ),
    ]
