# Generated by Django 5.0.14 on 2025-05-02 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiarios',
            fields=[
                ('id_beneficiario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('documento_identidad', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Programas',
            fields=[
                ('id_programa', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=50)),
                ('contraseña', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=15)),
                ('rol', models.CharField(choices=[('A', 'Administrador'), ('C', 'Consultor')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Contratos',
            fields=[
                ('id_contrato', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('etapa', models.CharField(choices=[('pre', 'Preejecucion'), ('eje', 'Ejecucion'), ('liq', 'Liquidacion')], max_length=20)),
                ('id_beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='victima_app.beneficiarios')),
            ],
        ),
        migrations.CreateModel(
            name='Entregas',
            fields=[
                ('id_entrega', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('fecha_entrega', models.DateField()),
                ('id_contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='victima_app.contratos')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='victima_app.productos')),
            ],
        ),
        migrations.CreateModel(
            name='BeneficiarioProgramas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='victima_app.beneficiarios')),
                ('id_programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='victima_app.programas')),
            ],
            options={
                'unique_together': {('id_beneficiario', 'id_programa')},
            },
        ),
    ]
