# Generated by Django 5.0.14 on 2025-05-06 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('victima_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='beneficiarios',
            name='apellido',
            field=models.CharField(default='nn', max_length=100),
        ),
        migrations.AddField(
            model_name='beneficiarios',
            name='direccion',
            field=models.CharField(default='nn', max_length=255),
        ),
        migrations.AddField(
            model_name='beneficiarios',
            name='email',
            field=models.EmailField(default='nn', max_length=254),
        ),
        migrations.AddField(
            model_name='beneficiarios',
            name='fecha_nacimiento',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='beneficiarios',
            name='fecha_registro',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='beneficiarios',
            name='telefono',
            field=models.CharField(default='nn', max_length=15),
        ),
        migrations.AddField(
            model_name='beneficiarios',
            name='tipo_documento',
            field=models.CharField(default='nn', max_length=50),
        ),
        migrations.AddField(
            model_name='contratos',
            name='fecha_registro',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='contratos',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='contratos',
            name='objecto',
            field=models.TextField(default='nn'),
        ),
        migrations.AddField(
            model_name='contratos',
            name='tipo_contrato',
            field=models.CharField(default='nn', max_length=50),
        ),
        migrations.AddField(
            model_name='productos',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productos',
            name='fecha_entrada',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='productos',
            name='fecha_salida',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='productos',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='productos',
            name='valor_unitario',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='programas',
            name='fecha_finalizacion',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='programas',
            name='fecha_inicio',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='programas',
            name='tipo_programa',
            field=models.CharField(default='nn', max_length=50),
        ),
        migrations.AlterField(
            model_name='beneficiarios',
            name='documento_identidad',
            field=models.CharField(default='nn', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='programas',
            name='descripcion',
            field=models.TextField(default='nn'),
        ),
    ]
